# Generated by Django 4.1.7 on 2023-03-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='claimed_by',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='claimed_date',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='founded_by',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='time',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='updated_at',
        ),
    ]
