# Generated by Django 4.1.7 on 2023-03-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_category_lostitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(default='', upload_to='upload/img'),
        ),
    ]
