# Generated by Django 4.1.7 on 2023-03-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_lostitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
