# Generated by Django 4.1.7 on 2023-03-26 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
