# Generated by Django 4.1.7 on 2023-03-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitem',
            name='image',
        ),
    ]
